# Generated by Django 6.0.5 on 2026-05-24 14:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap', 'SAP Fuel & Procurement'), ('utility', 'Utility / Electricity'), ('travel', 'Corporate Travel')], max_length=20)),
                ('source_row_id', models.CharField(blank=True, help_text='Original row identifier from source (SAP doc number, meter ID, trip ID)', max_length=255)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
                ('activity_type', models.CharField(choices=[('fuel_diesel', 'Diesel Fuel'), ('fuel_petrol', 'Petrol / Gasoline'), ('fuel_natural_gas', 'Natural Gas'), ('fuel_lpg', 'LPG'), ('electricity', 'Purchased Electricity'), ('travel_flight', 'Flight'), ('travel_hotel', 'Hotel Stay'), ('travel_ground', 'Ground Transport'), ('procurement', 'Procurement / Supply Chain')], max_length=50)),
                ('raw_value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('raw_unit', models.CharField(help_text='Original unit: L, kg, kWh, MWh, km, nights, etc.', max_length=50)),
                ('raw_data', models.JSONField(default=dict, help_text='Full original row as parsed — for full audit trail')),
                ('normalized_value_kwh', models.DecimalField(blank=True, decimal_places=6, help_text='Energy in kWh (for fuel/electricity; null for travel)', max_digits=20, null=True)),
                ('emission_factor', models.DecimalField(decimal_places=8, help_text='kg CO2e per raw unit, from DEFRA/EPA/IPCC', max_digits=20)),
                ('emission_factor_source', models.CharField(default='DEFRA 2023', help_text='Which emission factor database was used', max_length=255)),
                ('co2e_kg', models.DecimalField(decimal_places=6, help_text='Final emission in kg CO2e = raw_value * emission_factor', max_digits=20)),
                ('activity_date', models.DateField(help_text='Date the activity occurred (not upload date)')),
                ('period_start', models.DateField(blank=True, help_text='For billing-period data (utility); start of period', null=True)),
                ('period_end', models.DateField(blank=True, help_text='For billing-period data; end of period', null=True)),
                ('facility_id', models.CharField(blank=True, help_text='SAP plant code, meter ID, or office name', max_length=255)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('flagged', 'Flagged / Suspicious'), ('approved', 'Approved'), ('locked', 'Locked for Audit')], default='pending', max_length=20)),
                ('flag_reason', models.TextField(blank=True, help_text='Auto-generated reason if record was auto-flagged as suspicious')),
                ('analyst_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='emissions.emissionrecord')),
            ],
            options={
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('flagged', 'Auto-flagged'), ('approved', 'Approved'), ('locked', 'Locked'), ('edited', 'Edited'), ('rejected', 'Rejected')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('snapshot', models.JSONField(default=dict, help_text='Full record state at time of action')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='emissions.emissionrecord')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap', 'SAP Fuel & Procurement'), ('utility', 'Utility / Electricity'), ('travel', 'Corporate Travel')], max_length=20)),
                ('filename', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='emissions.tenant')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='emissions.ingestionbatch'),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='emissions.tenant'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'status'], name='emissions_e_tenant__5a7e62_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'scope'], name='emissions_e_tenant__80b9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['batch'], name='emissions_e_batch_i_f2aa5a_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['activity_date'], name='emissions_e_activit_c89ba8_idx'),
        ),
    ]
